const mealsMock = {
  meals: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strCategory: 'Side',
      strArea: 'Turkish',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      dateModified: null,
    },
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strCategory: 'Side',
      strArea: 'Turkish',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      dateModified: null,
    },
    {
      idMeal: '52785',
      strMeal: 'Dal fry',
      strCategory: 'Vegetarian',
      strArea: 'Indian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
      dateModified: null,
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      dateModified: null,
    },
    {
      idMeal: '52844',
      strMeal: 'Lasagne',
      strCategory: 'Pasta',
      strArea: 'Italian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
      dateModified: null,
    },
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      dateModified: null,
    },
    {
      idMeal: '52948',
      strMeal: 'Wontons',
      strCategory: 'Pork',
      strArea: 'Chinese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525876468.jpg',
      dateModified: null,
    },
    {
      idMeal: '52971',
      strMeal: 'Kafteji',
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
      dateModified: null,
    },
    {
      idMeal: '53013',
      strMeal: 'Big Mac',
      strCategory: 'Beef',
      strArea: 'American',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      dateModified: null,
    },
    {
      idMeal: '52769',
      strMeal: 'Kapsalon',
      strCategory: 'Lamb',
      strArea: 'Dutch',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg',
      dateModified: null,
    },
    {
      idMeal: '52802',
      strMeal: 'Fish pie',
      strCategory: 'Seafood',
      strArea: 'British',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg',
      dateModified: null,
    },
    {
      idMeal: '52854',
      strMeal: 'Pancakes',
      strCategory: 'Dessert',
      strArea: 'American',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
      dateModified: null,
    },
    {
      idMeal: '52887',
      strMeal: 'Kedgeree',
      strCategory: 'Seafood',
      strArea: 'British',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg',
      dateModified: null,
    },
    {
      idMeal: '52906',
      strMeal: 'Flamiche',
      strCategory: 'Vegetarian',
      strArea: 'French',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wssvvs1511785879.jpg',
      dateModified: null,
    },
    {
      idMeal: '52980',
      strMeal: 'Stamppot',
      strCategory: 'Pork',
      strArea: 'Dutch',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/hyarod1565090529.jpg',
      dateModified: null,
    },
    {
      idMeal: '53006',
      strMeal: 'Moussaka',
      strCategory: 'Beef',
      strArea: 'Greek',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
      dateModified: null,
    },
    {
      idMeal: '52791',
      strMeal: 'Eton Mess',
      strCategory: 'Dessert',
      strArea: 'British',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg',
      dateModified: null,
    },
    {
      idMeal: '52811',
      strMeal: 'Ribollita',
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xrrwpx1487347049.jpg',
      dateModified: null,
    },
    {
      idMeal: '52871',
      strMeal: 'Yaki Udon',
      strCategory: 'Vegetarian',
      strArea: 'Japanese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg',
      dateModified: null,
    },
    {
      idMeal: '52926',
      strMeal: 'Tourtiere',
      strCategory: 'Pork',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ytpstt1511814614.jpg',
      dateModified: null,
    },
    {
      idMeal: '52931',
      strMeal: 'Sugar Pie',
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg',
      dateModified: null,
    },
    {
      idMeal: '52963',
      strMeal: 'Shakshuka',
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g373701551450225.jpg',
      strTags: 'Egg,Brunch,Breakfast',
      dateModified: null,
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strCategory: 'Chicken',
      strArea: 'Thai',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      dateModified: null,
    },
    {
      idMeal: '52781',
      strMeal: 'Irish stew',
      strCategory: 'Beef',
      strArea: 'Irish',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg',
      dateModified: null,
    },
    {
      idMeal: '52832',
      strMeal: 'Coq au vin',
      strCategory: 'Chicken',
      strArea: 'French',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg',
      dateModified: null,
    },
  ],
};

export default mealsMock;
